### ISSUE TITLE
Certain Lecture exercises not loading: Unexpected Error Cannot return null for non-nullable field Board.validations.

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#1]
The following exercises from the Lecture schedule cannot load, all give the same error:
> Unexpected Error Cannot return null for non-nullable field Board.validations.

### Lecture 3 
- Clara Cleaner with while loop
http://staging.claraworld.net/exercise/clara-cleaner-with-while-loop--lecture-3--lectures?e=ErtbS7bscnpNNK5PQ&p=n7fNujc47XwSAvYeR&i=Rc3oLZ7JM7uXsDfcw

### Lecture 5
- Clara Makes Friends
http://staging.claraworld.net/exercise/clara-makes-friends--lecture-5--lectures?e=fvkkiafMd3SBY9cLM&p=hwQhhc7rrGbbgsmDR&i=Rc3oLZ7JM7uXsDfcw

### Lecture 6
- Average
http://staging.claraworld.net/exercise/average--lecture-6--lectures?e=MPavvmpXuqkCe7ymG&p=xCrg2EHYTkNJbLdvC&i=Rc3oLZ7JM7uXsDfcw

### Lecture 7
- Bug Navigation
http://staging.claraworld.net/exercise/bug-navigation--lecture-7--lectures?e=yRCnA3QvAWBGRB5bQ&p=xMMymQW9nfuuaCQiv&i=Rc3oLZ7JM7uXsDfcw
- Random Walk	
http://staging.claraworld.net/exercise/random-walk--lecture-7--lectures?e=PuGWcWQbmni3kAp5E&p=xMMymQW9nfuuaCQiv&i=Rc3oLZ7JM7uXsDfcw

### Lecture 8
- Clara_MakesFriends_Array
http://staging.claraworld.net/exercise/clara_makesfriends_array--lecture-8--lectures?e=StCaLmRjvLniLGY63&p=zpdNrgSqNf69Huh5b&i=Rc3oLZ7JM7uXsDfcw

### Lecture 9
- Factorial
http://staging.claraworld.net/exercise/factorial--lecture-9--lectures?e=KmJoGF6HRHbX4XzMK&p=uizfREFAwNYHXy6SD&i=Rc3oLZ7JM7uXsDfcw

**Comment by tomitrescak** [comment]
fixed by tomitrescak/clara#b9e695c

**Comment by tomitrescak** [comment]
Tested on staging and it works. Let me know if needs to be reopened.

**Comment by Dean-P** [comment]
They all open on my end 👍
