### ISSUE TITLE
Due date for practicals is shown incorrectly

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#101]
The due date for practicals shows the next day after the submission deadline, which creates confusion. For example, Spring 2021, Practical 2 is due on the 6th of August, but when you open the practical it shows 7th of August at the bottom. Please correct it so that it shows the 6th of August instead.

**Comment by tomitrescak** [comment]
This is the way I display it now:

![image](https://user-images.githubusercontent.com/2682705/127257249-e0467f90-0152-468a-8c72-d8781327f080.png)
