### ISSUE TITLE
Staging version: Multiple problems

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#103]
There are issues with my Spring 2021 solutions.
Major Assignment doesn’t start. 6.1 solution doesn’t compile.
Check them out through Spring 2021 -> marking.

My Solution for Book -> Chapter 10 -> Clara Ant Solution doesn't work.
My Solution for Book -> Chapter 10 Exercises -> Pacman freezes
Level complete problem in Book->Chapter 10 Exercises -> Socoban. See https://github.com/tomitrescak/clara-support/issues/91

**Comment by antonwsu** [comment]
It's not yet fixed.
Spring 2021 works. 
Book -> Chapter 10 Exercises -> Pacman -> sounds don't work properly. In particular isPacmanIntroStillPlaying() and playPacmanIntro() don't work. You can test it on my solution.
My Solution for Book -> Chapter 10 -> Clara Ant Solution still doesn't work.
Sokoban still doesn't work. See #91

**Comment by tomitrescak** [comment]
- [ x] Spring 2021 works.
- [x] Book -> Chapter 10 Exercises -> Pacman -> sounds don't work properly. In particular isPacmanIntroStillPlaying() and playPacmanIntro() don't work. You can test it on my solution. **THERE WAS NOTHING CHANGED SOUND WISE** In my browser all works as expected. Could be a network issue for you**
- [x] My Solution for Book -> Chapter 10 -> Clara Ant Solution still doesn't work.
- [x] Sokoban still doesn't work. See #91

**Comment by antonwsu** [comment]
Book -> Chapter 10 Exercises -> Pacman. I tested my solution in two browsers (Safari and Chrome). Everything works if I run it from claraworld.net and doesn't work in either browser if I run staging.claraworld.net. I hear no sounds and ghosts don't start moving (because they are waiting for the intro sound to finish playing).

**Comment by antonwsu** [comment]
Clara Ant works on staging.

**Comment by tomitrescak** [comment]
As per Sokoban, you are initializing the Array for houses as `houses = new BoardTile[1];` 
But there are 4 houses ... so I fixed the initialisation. 

This calls for having some possibility to define Lists, which are currently not supported. I'll open a new ticket for that one
