### ISSUE TITLE
Pacman Assignment sound problems

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#105]
Sound issues are still there as per: https://github.com/tomitrescak/clara-support/issues/103.  I tested my solution in two browsers (Safari and Chrome). Everything works if I run it from claraworld.net and doesn't work in either browser if I run staging.claraworld.net. I hear no sounds and ghosts don't start moving (because they are waiting for the intro sound to finish playing). I certainly don't have network issues causing this.

**Comment by tomitrescak** [comment]
Anton ... all works on my end .. can you check your development console if you see any errors there? There is literally NO change on sound handling between staging and live

**Comment by antonwsu** [comment]
![Screen Shot 2021-07-28 at 1 32 08 pm](https://user-images.githubusercontent.com/26546072/127259396-f17c37ab-4a50-4176-a50c-2e7cdefcaa01.png)

**Comment by tomitrescak** [comment]
There you go. It shoudl be ok on live. I'll close it for now and will reopen if re-appears on live.
