### ISSUE TITLE
Compiler bug

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#107]
Inserting the method below anywhere in your code would disable the "run" button and no error will be reported. This is due to missing "int" in the for-loop and the lack of curly brackets. Having no curly brackets should be allowed.

    void initWorld()
    {
        for (x = 0; x < WORLD_WIDTH; x++)
            for (y = 0; y < WORLD_WIDTH; y++)
                if (Clara.getRandomNumber(2) == 1)
                    putLeaf(x, y);
    }

**Comment by tomitrescak** [comment]
I cannot reproduce this.

1. If x is not defined I get the correct message:
 
![image](https://user-images.githubusercontent.com/2682705/152451308-b5f6d21f-6a50-427b-bf15-18204716ab37.png)

2. If x is defined globally, the button is enabled:

![image](https://user-images.githubusercontent.com/2682705/152451530-6dcaa5cb-2959-4b2e-bd14-aee3f3d89307.png)

But there IS a bug  when there is no int as the generated code is incorrect

**Comment by tomitrescak** [comment]
Fixed, covered with the following test case:

```ts
it('variable can be introduced globally', () => {
  expect(`
    int i;
    void run()
    {        
        int length = 10;
        for (i = 0; i < length; i++ ) 
          i++;
    };

  `).toCompileMethodsTo(`
    constructor() {
      this.i = 0;
    }
    run() {
      let length = 10;
      for (this.i = 0; this.i < length; this.i++) {
        this.i++;
      }
    }
  `);
});
```
