### ISSUE TITLE
Feature request: Info about a student 

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#109]
This is low priority, but it would have been handy to see all submissions from a student. At the moment we have to open each practical and search for the student there. It would be more convenient to be able to search for a student name and see all marks and all submissions across the entire schedule.

**Comment by tomitrescak** [comment]
This has been available for many years now Anton ;p
Just use the "Results" tab on a marking screen:

![image](https://user-images.githubusercontent.com/2682705/129990577-2438964d-f2b7-4e5f-8366-abd0e2cb933a.png)
