### ISSUE TITLE
Swapped coordinates in given functions in Practical 6 Bonus Problem

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#11]
The supplied code for the bonus has functions that each call ```this._board.getSprite(int row, int column)``` using the x coordinate for row and the y coordinate for column, leading to tiles being placed diagonally opposite of where they should be placed.

This happens in each of the 'put', 'on' and 'remove' functions:
```
void putLeaf(int x, int y) 
void putFire(int x, int y) 
void putAsh(int x, int y)
boolean onLeaf(int x, int y)
boolean onFire(int x, int y)
boolean onAsh(int x, int y)
void removeLeaf(int x, int y)
void removeFire(int x, int y)
void removeAsh(int x, int y)
```

Each of them do:
```
if (this._board.getSprite(x, y) != null) {
            any fire = this._board.getSprite(x, y);
    .
    .
    .
}
```

Where the arguments should be swapped:
```
if (this._board.getSprite(y, x) != null) {
            any fire = this._board.getSprite(y, x);
    .
    .
    .
}
```

I think this can only be altered by an admin on the website itself.

**Comment by tomitrescak** [comment]
@antonwsu Please revisit this exercise, or make Dean the admin to fix it. Thanks.

**Comment by antonwsu** [comment]
@Dean-P I can see that you have admin rights for WSU. Please correct this. Please just swap things around. Don't replace getX() and getY(), since I use these in multiple other places.

**Comment by Dean-P** [comment]
@antonwsu I don't seem to have the modify button on the new website (I had one before). Even when I could modify, I could alter the properties for the schedule but I could not edit the exercises themselves.

![admin](https://user-images.githubusercontent.com/9068794/108178098-295db580-7158-11eb-9ec1-ef592fc278e3.png)

**Comment by tomitrescak** [comment]
Dean, in your user menu (the Dean Preston menu on the right) is "Edit Mode" button.

**Comment by Dean-P** [comment]
Thanks for that. I updated the inner functions and the initial sample code. The commands still use the (x,y) format for input but now the coordinates refer to the correct tile.
