### ISSUE TITLE
Problems with saving files on staging

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#110]
Multiple issues on staging with files not saving and saving and then disappearing reported by David Coleman while working on the Pacman Assignment (using staging) from Summer 2021.
Save File - Failed to Fetch! See screenshot below.
![image](https://user-images.githubusercontent.com/26546072/129461013-72fc8ceb-5e1e-4fad-a205-bd3359da2abd.png)

**Comment by antonwsu** [comment]
Further update from David. The problem of not being able to save edits has been fixed!
The internet guys here refreshed our profile on one of their servers and now I can finally save edit files again.
So it was a problem at this end. Should we close this for now?

**Comment by tomitrescak** [comment]
Yes, let's close this
