### ISSUE TITLE
Feature request: Highlighting the submitted edit in History

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#111]
It would have been very useful to highlight the submitted version of each assignment in edit history. This would help a lot with running misconduct meetings. Students occasionally argue that they have never submitted this or that their submission was something else.

**Comment by tomitrescak** [comment]
Done, now yoi have a purple indicator showing you that this is the submitted version:

![image](https://user-images.githubusercontent.com/2682705/152460565-4f35acf4-9f96-4111-b98f-57887603d1cf.png)
