### ISSUE TITLE
Clara's speed settings sometimes disappear.

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#112]
I noticed that speed setting sometimes disappear in Clara's World and one of the tutors reported this as well. I'll try to lookout for scenarios when this happens and will add comments here once I do. This happens on staging as well.

**Comment by tomitrescak** [comment]
It disappears when you disable it in your exercise settings

**Comment by tomitrescak** [comment]
I'll close it for now as it does not seem to be an issue anymore
