### ISSUE TITLE
Unable to delete accounts from Organisation Admin page

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#113]
<img width="929" alt="Screen Shot 2021-09-09 at 9 44 10 pm" src="https://user-images.githubusercontent.com/26546072/132679867-2a83c82d-8da2-4c30-9d04-d772dbb0cd8b.png">
Can't delete those email addresses that were  accidentally created.

**Comment by tomitrescak** [comment]
This is fixed on staging ATM, will be fixed once we flip staging to production.
