### ISSUE TITLE
Clara's position is incorrect after dragging inside a scaled window.

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#114]
Open a problem, resize the window. Drag Clara around. She will not end up in the position where you intended her to be.

**Comment by tomitrescak** [comment]
I could not replicate this in Chrome or Firefox and the position always worked

![clara](https://user-images.githubusercontent.com/2682705/132775540-15dda374-f628-40b7-928c-102a5e60303c.gif)

**Comment by antonwsu** [comment]
I could not reproduce it on Chrome, but it's always there in Safari: https://youtu.be/65ZxHZyVql4

**Comment by tomitrescak** [comment]
Once I’ll get a new Mac I will be able to address all Safair issues.

**Comment by tomitrescak** [comment]
I think I solved this on staging. There really was a bug that should be addressed now.
