### ISSUE TITLE
Compiler problems with calling a method and a variable the same

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#118]
A student has submitted the code below, where a variable and a method share the same name. The code doesn't run (run button grayed out) but the error is not reported. 

    int claraAnimation = 0;

    public void act()
    {
        claraMovement();
        claraAnimation();  
    }
    
    void claraAnimation()
    {
        claraAnimation++;

        if (claraAnimation%60 == 0)
        {
            animate();
        }   
    }

**Comment by tomitrescak** [comment]
Solved:

![image](https://user-images.githubusercontent.com/2682705/152463403-bbc54e57-a6ba-48ab-9bfc-7724676d8bc0.png)
