### ISSUE TITLE
Tutors can accidentally reset student files 

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#119]
While helping a student Tad realised that pressing "Reset Files" on a student's files will not only reset the local copy of the tutor, but will also reset the files globally for the student. Desired functionality is that all changes done by the tutor (including resetting files) are only done to the local copy and student files are not affected.

**Comment by tomitrescak** [comment]
How does a system know that it is tutor making changes? ...
For this part you have Undo functionality for local files.

I would not change a thing.

**Comment by antonwsu** [comment]
I don't know how it is on your end, but I can currently find a submission of any student, make changes, run, make more changes, etc. but when the student logs in the changes are not visible. So, I seem to be working with a local copy instead of changing the code of the student. This idea should be extended on resetting files. Otherwise we will be getting too many emails, since the system is not full proof. Tad discovered this bug as he tried to help a student who deleted parts of the original template code in one of the classes.

**Comment by tomitrescak** [comment]
Anton, I am not sure what you want. 
1. You cannot overwrite student changes with your changes, that makes sense I hope 
2. The reset button is there to reset files to ORIGINAL format
3. ... I really do not know what do you want. If a tutor needs to see again student files he needs to undo his changes or just reload the page

**Comment by antonwsu** [comment]
> Anton, I am not sure what you want.
> 
> 1. You cannot overwrite student changes with your changes, that makes sense I hope
> 2. The reset button is there to reset files to ORIGINAL format
> 3. ... I really do not know what do you want. If a tutor needs to see again student files he needs to undo his changes or just reload the page

All I want is that tutor pressing "Reset Files" has no impact on the student's code. IMO, the fact that a tutor can reset students files is a bug. What happened to Tad was: 1) He pressed "Reset Files" while viewing a student's submission. 2) The student lost his code. This shouldn't happen.

**Comment by tomitrescak** [comment]
So ... "reset files" will "not reset files" ... just call me because I really do not understand. Or you just want prohibit tutors from resetting student files?

**Comment by tomitrescak** [comment]
I can just hide the "reset files" button from the tutor without modifying it functionality .. will that do ?

**Comment by antonwsu** [comment]
Yes, Tomas, this will do. Tutors should not be able to reset student files.

**Comment by antonwsu** [comment]
To explain where I'm coming from... Imagine one of Inma's tutor's accidentally erasing student code. You will be getting all those emails for no good reason. Since we are gradually inviting more organisations, we should search for ways to reduce the number of emails that we receive.

**Comment by tomitrescak** [comment]
Solved but considering there is a GIANT warning that that action is undoable and that you should not do it unless sure, I spent WAAAAAY too much time on fixing this.

![image](https://user-images.githubusercontent.com/2682705/152467155-51840c42-983a-407c-9fd7-83ffd67d3452.png)
