### ISSUE TITLE
Comments in Marking View don't update after first student

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#12]
In Marking View, the comments for a student will persist when viewing other students' comments.

i.e.,

Open a comment for a student, which works as intended:
![correct comment](https://user-images.githubusercontent.com/9068794/107161008-d4020580-69ed-11eb-932a-31abd9042702.png)

Then open comments for another student and the comments are unchanged:
![incorrect comment](https://user-images.githubusercontent.com/9068794/107161013-d9f7e680-69ed-11eb-8e81-2975d917a268.png)

**Comment by tomitrescak** [comment]
You are the best bug reporter out there! Thanks! I'll deal with it soon

**Comment by Dean-P** [comment]
Just adding onto this, it looks like comments always load as empty now. I sent myself a test comment and got the email notification, but I cannot see the comment I made when I go to the marking view.

I cannot see any existing comments from students either (in any practical).

**Comment by tomitrescak** [comment]
Dean, I tested this and all works ... can you check?

**Comment by Dean-P** [comment]
All good on my end, thanks.
