### ISSUE TITLE
Embedding Clara's World doesn't work well

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#121]
I tried embedding Clara's World into a vuws exam. More than half of the students struggled with this for various reasons.
We need to think of a better way of handling those security issues.

**Comment by tomitrescak** [comment]
This was a tricky one to solve. The solution now is that for any EMBEDDED iframe you add `&embed=true` to the URL. For example:

http://localhost:3000/exercise/problem-1_1-getting-started--practical-1-introduction-to-clara-s-world--spring-2021?e=9C63xvxNqGBPaxc5c&p=c3HfyywsuWSoMoGxv&i=szxPuSfdtTKsPXQ5a&embed=true

Now, the refresh token will be kept in the session storage, as a result, the session is kept as long as user keep working in the same Tab. If user opens a new tab he will have to re-login. But I believe this solution should be sufficient, as this solution will maintain session even when changing URLs in the same domain. 

Please test and reopen if necessary. 

PLEASE CONFIRM ON VUWS whether this works. Thanks!
