### ISSUE TITLE
Additional user permissions: feature request

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#122]
I would like to have organisation admins, who can only clone exercises and are unable to modify existing exercises (only cloned or new exercises). This is to do with new organisation admins not knowing how the system works and then breaking our exercises that work.

It would also be great to have users who are not admins (e.g. tutors) who have admin permissions for schedules. For example, Tad is coordinating the Summer session. I would like to give him admin rights over the corresponding schedule.

**Comment by tomitrescak** [comment]
Anton, the current permission system is quite flexible.
If you have a situation where no authentication is required, you can use "Groups". That is, you create a "Group" that anyone can join and you specify permissions for that group.

If you have a situation where authentication is required, such as the one with Tad, you can use "Organisations". That is, you create a new organisation (e.g. "WSU Tutor Admins") and you see the password to allow to join this organisation. Then on the schedule you set write permissions for this organisation.

Check out how I allowed any member of PASS group to have the ability to modify the Spring 2021 schedule (not on live server)

![image](https://user-images.githubusercontent.com/2682705/152468322-5b8bb8d5-dfbe-4f8d-8067-c91498aafda8.png)

And this is what my Student user, member of pass group sees:

![image](https://user-images.githubusercontent.com/2682705/152468359-f5a79a1c-2f9f-4d59-9efc-4db5a76a941a.png)
