### ISSUE TITLE
World does not show when Creating Modifying

### ISSUE THREAD

**Issue by drtaguewsu** [tomitrescak/clara-support#130]
When wanting to update existing worlds the board does not show for editing. Tried Chrome, Firefox, Edge, and Safari. Doesn't work for any. Wanting to update practicals for Autumn 2023

<img width="1162" alt="Screenshot 2023-02-21 at 5 11 09 pm" src="https://user-images.githubusercontent.com/54823859/220262432-81bb752b-a73b-470e-83c3-d49a9eb1003d.png">

When changing the rows and columns it doesn't fix the issue. Unexpected behaviour occurs when having a positive value for column for and a 0 for rows. 

<img width="1153" alt="Screenshot 2023-02-21 at 5 24 12 pm" src="https://user-images.githubusercontent.com/54823859/220264276-c44f15e0-c6da-437c-889e-4ad49df6f0b8.png">

It doesn't matter what exercise, this occurs for all for all browsers.

**Comment by tomitrescak** [comment]
Rhys, I got the shittiest solution, but I really do not want to support the old version as we really need to get the new version out of the door.

But, all you need to do is to open the screen where the board is diappeared and paste this into your web console

```
$('.css-15d0bjv').style.minHeight = '300px';
$('.css-15d0bjv').style.minWidth = '300px';
```

**Comment by rhystague** [comment]
Totally understand not wanting to touch the old code base. 

Might be a shit solution, but it's a solution 💪.
