### ISSUE TITLE
Sorting Schedules on homepage differs between Chrome and Firefox

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#14]
On the homepage, the schedules can be sorted by start date (asc, desc) or by name (asc, desc). Sorting by name works the same on either browser but sorting by date gives different results between the two. Chrome seems to give the correct order, but Firefox has quite different results.

Side-by-side comparisons, Chrome on the left and Firefox on the right:
Start Date Descending (default):
![start date desc](https://user-images.githubusercontent.com/9068794/107315522-ffb6e580-6aea-11eb-9056-d462bd988222.png)

Start Date Ascending:
![start date asc](https://user-images.githubusercontent.com/9068794/107315535-06455d00-6aeb-11eb-8d74-39e50ecf2c96.png)

Name (ascending), works as intended:
![name](https://user-images.githubusercontent.com/9068794/107315612-2d039380-6aeb-11eb-8e88-408f4855e02f.png)

**Comment by tomitrescak** [comment]
Hi, I could not replicate this ;((( It works fine for me in firefox.

![image](https://user-images.githubusercontent.com/2682705/107750659-6e58a500-6d70-11eb-9af3-6a95ce900072.png)
