### ISSUE TITLE
Major Assignment has broken features

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#15]
This is a critical issue if the staging version is being rolled out this weekend. Students with extensions won't be able to continue working on the new version of the site.

I don't know if these should be separate issues but the Major Assignment cannot be completed on the staging version.

- Sounds do not play
I tested `playPacmanIntro()` and `playLeafEatenSound()`. My sound is working for other tabs and the site is not muted.

- Functions that interact with the board like `putLeaf()`, `onLeaf()` and `onMushroom()` trigger an error: World #1: this._board.world.getTileByName is not a function. `treeFront()` always returns false which, from what I understand, is related to the same error.

**Comment by tomitrescak** [comment]
Can you check if all works? 
I did not do anything with the sound though .. it worked for me :/
Maybe try a page refresh.

**Comment by Dean-P** [comment]
The sound does not work for me. I tested it on two Windows 10 machines, both on Chrome and Firefox. Multiple refreshes, logins and reboots. The sound works on other pages for both machines.

**Comment by tomitrescak** [comment]
Can you give me access to your account? All works for me. I hate when that happens

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Dean-P** [comment]
Hi Tomas,

Email: d.preston@westernsydney.edu.au
Pass: tAP8keR5ju6pSFP

Thanks,
Dean

________________________________
