### ISSUE TITLE
Being logged out all the time

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#18]
I'm checking links in the book. Every second time I click on one I get a message "Unexpected Error Not authorised!" because I'm being logged out. I'm not actually logging out.

**Comment by antonwsu** [comment]
Example of definite logging out. Go to Book -> Chapter 1 -> Problem 1 -> Click on "Results" in the top right corner -> Bye Bye.
<img width="833" alt="Screen Shot 2021-02-16 at 4 31 13 pm" src="https://user-images.githubusercontent.com/26546072/108022355-8122f080-7074-11eb-980a-af03c3206d18.png">

**Comment by antonwsu** [comment]
Sometimes logging out happens after opening a new tab and navigating to claraworld.net.

**Comment by tomitrescak** [comment]
Yah, this is heavy shit from Guang's deployment .. it works fine if you use www.claraworld.net ... keep using that now.

**Comment by tomitrescak** [comment]
The problem is that I cannot set the serverside cookie due to multiple proxies that we use. I'll try to deal with it, but for now please use the www version

**Comment by tomitrescak** [comment]
Ok, fixed with more robust client cookie solution
