### ISSUE TITLE
Issues with setting a schedule to be visible by multiple organisations

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#20]
I'm trying to have book schedules available to both WSU and Book users, but can't figure out how to do it.

**Comment by antonwsu** [comment]
My understanding is that this is supported by pressing + and adding a new organisation, but it doesn't work because Groups filed must be specified. I don't really know what to put there.
<img width="1107" alt="Screen Shot 2021-02-16 at 4 36 30 pm" src="https://user-images.githubusercontent.com/26546072/108022762-4b323c00-7075-11eb-90d0-fb3664aeac17.png">

**Comment by tomitrescak** [comment]
That is NOT possible. You cannot add access to multiple organisations. 
This is what we talked about before and you agreed that content is only accessed in one organisation.
What you can do is to define a "someGroup" in both WSU and Book organisations and then give access to this group.
then whoever joins the "someGroup" in WSU will obtain access to the organisation.

**Comment by antonwsu** [comment]
OK, understood. Scrapping this.

**Comment by tomitrescak** [comment]
I actually made it work by joining the possibility to specify groups and organisations in the same field:

![image](https://user-images.githubusercontent.com/2682705/108138313-d3feb580-7111-11eb-94b9-edae761c3067.png)
