### ISSUE TITLE
Returning back after editing a practical gets you permanently stuck in edit mode

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#25]
How to reproduce:
Go to Book schedule.
Enable edit mode and edit one of the practicals.
Click "Back".
You will be stuck in edit mode, and would have to return back to claraworld.net to see the practical. 
Desired behaviour is returning back inside the schedule without being in edit mode.
<img width="1214" alt="Screen Shot 2021-02-16 at 5 11 09 pm" src="https://user-images.githubusercontent.com/26546072/108025184-24c2cf80-707a-11eb-8d7b-78d4f5d23dfa.png">

**Comment by tomitrescak** [comment]
I am not sure what you mean. There is no "Back" button in practicals.

**Comment by tomitrescak** [comment]
When I click the browser's back button I am back in the schedule

**Comment by tomitrescak** [comment]
If you mean that from schedule admin mode you go to admin of practicals, that is the desgned behaviour

**Comment by tomitrescak** [comment]
You can always just delete "admin" from the url to get back to the normal view.

If you have some better idea pleaee let me know. maybe we

**Comment by antonwsu** [comment]
Yes, sorry, what I meant was clicking on the link above. In the past this link would take you to normal mode (not admin). This is actually the desired behaviour. It's against common sense for me to be in edit mode after clicking this link. This is an operation that I do quite frequently: Clicking on a schedule and modifying individual exercises there. After modifying the exercise I want to see how it lo
<img width="408" alt="Screen Shot 2021-02-17 at 4 35 54 am" src="https://user-images.githubusercontent.com/26546072/108100544-27eda800-70da-11eb-97a0-a95c19809e4d.png">
oks like after changes and clicking this link was handy. Returning to edit mode is not useful at all.
If I click on Book I expect to see the Practicals in this schedule and then select the next one and find the problem that needs editing.

**Comment by tomitrescak** [comment]
I did it your way, but it is questionable. Yes, in the maintenance mode this may be desirable at time, but in the design mode it will increase the number of clicks you have to do two-fold. Let's see if you like this in the long run. For me it it annoying ;) But live version is now fixed.
