### ISSUE TITLE
Resetting files -> Hitting run -> Refreshing browser causes a crash

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#26]
I produced a solution in Book Chapter 1 exercise. After resetting to empty code I was able to run the old solution (despite the code being empty). After hitting refresh the browser starts loading and never finishes.

**Comment by tomitrescak** [comment]
Yes, it resets the code but the compilation is there still from the previous code. The moment you type the new command the code recompiles. 

>>  After hitting refresh the browser starts loading and never finishes.

Does this mean that you are no longer able to work in claraworld ?

**Comment by antonwsu** [comment]
Yep, have to close the tab and start again.

**Comment by antonwsu** [comment]
I tried to reproduce it again to attach a screenshot. It no longer crashes the browser after refresh, but it reverts back to the old code after refreshing, which shouldn't be the case. How to reproduce: type nonsense code, run it, click reset files, refresh -> nonsense code is back.

**Comment by tomitrescak** [comment]
Question is .. do you want it to automatically save after reset? There is no coming back fro this. If you hit it accidentally, you still can refresh the page to be back in your old code.... but if you want to autosave and compile that is not an issue.

**Comment by antonwsu** [comment]
You would have it in history, would you not?

**Comment by tomitrescak** [comment]
Yes, but you will not be able to UNDO this as the model is completely replaced. Anyways, I just added a warnign that this action is permanent.
