### ISSUE TITLE
After fixing the issue with adding images all images are broken everywhere else.

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#27]
Now descriptions in all practicals no longer have images.
<img width="820" alt="Screen Shot 2021-02-17 at 4 54 24 am" src="https://user-images.githubusercontent.com/26546072/108102167-4e144780-70dc-11eb-8456-b72f0fa2521b.png">

**Comment by tomitrescak** [comment]
Fixed.
