### ISSUE TITLE
Problems with permissions

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#29]
For some reason I can see submissions of all students for all practicals and the Major Assignment from my student account. How to reproduce: Login with an account that has WSU as organisation -> Go to practical -> Marking -> All students.

**Comment by antonwsu** [comment]
I tested this with Summer 2021._

**Comment by antonwsu** [comment]
I created a new WSU account (30022071@uws.edu.au) and this doesn't happen there, but I can still access student files through my non-admin account at a.bogdanovych@westernsydney.edu.au. This account is not listed as admin for WSU (a.bogdanovych@uws.edu.au is my admin account).

**Comment by tomitrescak** [comment]
There is no problem, your user is a tutor: "a.bogdanovych@westernsydney.edu.au". All tutors have access to marking.

**Comment by tomitrescak** [comment]
Here is a screensho

![image](https://user-images.githubusercontent.com/2682705/108178739-e5b77b80-7158-11eb-8f13-4acf8cb026f4.png)

**Comment by antonwsu** [comment]
@tomitrescak, I do not appear as a tutor for Summer 2021 and am not listed as admin for WSU.

**Comment by tomitrescak** [comment]
As I said, you might have added yourself by mistake and then removed yourself. But the role stays.

I have just pushed a latest version, and now in the "Organisation" screen you can review all organisation users that have specific roles. You can revoke those roles.

![image](https://user-images.githubusercontent.com/2682705/108188863-354f7480-7164-11eb-861a-d2188fae6b98.png)

**Comment by tomitrescak** [comment]
Your Anton is there as well ...

That being said, we will probably need a finer grain control over what data does a tutor see.
This would include specifying "Tutor" per "Schedule". So tutors can only see the schedule data to which they are assigned.

Thus when you create a new schedule you have to addits tutors as well.

This is a major back end change though and will take some time and needs to be properly tested.
Do you want this change? I can create a new ticket for it.

**Comment by antonwsu** [comment]
@tomitrescak It would make sense to add tutors per schedule. This is not urgent though. What threw me off is that we actually do specify tutors for every schedule. If I edit a schedule (e.g. Summer 2021) I see the tutors there. I assumed that only those have tutor rights for a particular schedule and because my name isn't listed this means I shouldn't have the rights to mark.
<img width="546" alt="Screen Shot 2021-02-18 at 5 15 32 am" src="https://user-images.githubusercontent.com/26546072/108248899-83866700-71a8-11eb-9800-a43ccecd8cd3.png">
