### ISSUE TITLE
Not listed as a tutor or admin in Clara's World, but can see student mark

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#30]
This is related to https://github.com/tomitrescak/clara-support/issues/29. I'm not actually listed as a tutor for Summer 2021 or admin in WSU, but can see student submissions and mark them. I'm somehow listed as a tutor in the database and I wonder why. This could be a serious security issue.

**Comment by tomitrescak** [comment]
That is NOT a security issue, you must have mistakingly added at some point your user as a tutor. The tutor is forever.

**Comment by tomitrescak** [comment]
If you really need we can add a screen where you will be able to review roles .... but the ONLY way to get a tutor status is to add him to the list of tutors at some schedule

**Comment by tomitrescak** [comment]
I am going to implement stricter control of what tutors can see .. it is not too much actually. Will post back once it is done.
