### ISSUE TITLE
Tutor still has access to marking after being deleted from a Schedule

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#31]
I'm testing the staging version. I was able to sign in with my @westernsydney account (student) and initially had no access to marking. After entering with an admin account and adding my student account as a tutor to Book and Summer 2021 I was able to access marking. The issues is that when I deleted myself as a tutor from Summer 2021 I can still access marking there. Moreover, I can also access marking for schedules where I was never registered as a tutor (such as https://staging.claraworld.net/schedule/wsu-city-campus-s1-alternate-assessment-?i=2yE7YzzewoaDu8Fse).

**Comment by tomitrescak** [comment]
Please give me access to this user .. this is merely impossible on the code level wwhat is happening to you
Can you also refresh page?

**Comment by tomitrescak** [comment]
I need username and paassword .. thanks

**Comment by tomitrescak** [comment]
I replicated your configuration but my user does not see marking. I will need your user to check

**Comment by tomitrescak** [comment]
Also make sure you refresh your page. When you change something in one browser is not replicated in another due to caching. This does not explain though that you see city campus marking. It is almost impossible though .. so I really wonder what is going on

**Comment by tomitrescak** [comment]
Ah, I see what is going on, you are using https ... this is redirected to the main site. You have to use http://staging ... I’m gonna close this. But please keep using staging

**Comment by tomitrescak** [comment]
Check if on correct staging all works, reopen if necessary

**Comment by antonwsu** [comment]
@tomitrescak I sent you account details via email. At the moment I can't see anything inside Summer 2021 schedule after deleting the tutor from this schedule. I can normally see the content when logging in on the production website (claraworld.net).

**Comment by tomitrescak** [comment]
Can you try now? There was a bug with practicals view.

**Comment by antonwsu** [comment]
Still can't see it.

**Comment by tomitrescak** [comment]
Anton, I just got confirmation from students that it works ... I also tested with your user and it works. Please check again and make sure you are using a correct url.
