### ISSUE TITLE
Using Step/Continue in debugger does not scroll the editor to the current line

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#32]
When the next line in the program is off-screen, the debugger used to scroll the editor to show the line. This doesn't happen in the new version. The same thing happens with Continue (not shown).

![video demo](https://i.gyazo.com/0c779875edaf8a6ee607024dc40326bb.gif)

**Comment by tomitrescak** [comment]
I will look at it, how do you like the new debugger.... was not sure where to position it .. up or down.

**Comment by tomitrescak** [comment]
Hi, fixed on staging ... will move to live over weekend if you guys do not report any issues with staging till then.

**Comment by Dean-P** [comment]
Thanks, it is working for me. 

I don't mind the debugger at the top since that's where it was previously. I think the step/continue buttons could be labelled, though. I don't think many students will understand them by the symbol alone.
