### ISSUE TITLE
Student has no practicals on Summer 2021 schedule page

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#33]
The page loads correctly for me and Shahzad (tutor) but one student has reported that their page loads with no practicals, even after logging out and restarting the browser.

The student is Alex Weng (18979350). This only just started today.

Screenshot from Alex:
![clara not working](https://user-images.githubusercontent.com/9068794/108327936-1c0bfe00-7220-11eb-920a-f9dbd95cd696.PNG)

**Comment by tomitrescak** [comment]
Dean, Alex

 

Can you please try again?

There was a bug

 

Thanks

**Comment by Dean-P** [comment]
Yeah, the student said it works for them now 👍

**Comment by antonwsu** [comment]
I had the same issue. Works for me now too.
