### ISSUE TITLE
Making problems and schedules read only

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#35]
This is a feature request. My biggest worry with letting new people and organisations in is that they will stuff up my past or present schedules by making changes. 

What I mean is that someone might copy an entire practical into their schedule and then decide to modify individual problems inside and accidentally delete or stuff up the original problem. They may decide to add/delete problems from a practical they copied and half way through the semester my students would see their work disappear (this has actually happened to Chris in the past when I did some modifications to Practicals 7).

We need a mechanism to ensure that once a schedule is created it is safe from outside intruders. Whatever changes made outside should not affect the original. Let's have a discussion on what is the best way to protect these.

**Comment by tomitrescak** [comment]
Anton, that is why we have permissions. You can allow people to to read / write / add new items. Thus no one will ever be able to modify your stuff unless you allow them.
