### ISSUE TITLE
Email address with capital letters are treated as different to those with lower case letters

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#38]
One of the tutors tried to login using S.Farhad@westernsydney.edu.au instead of s.farhad@westernsydney.edu.au and could not log in and could not recover password. He was able to login with s.farhad@westernsydney.edu.au after contacting me. It seems that these two are treated as different email addresses.

**Comment by antonwsu** [comment]
Tad has reported this bug as well when trying to recover his password.

**Comment by tomitrescak** [comment]
Fixed ... this migh have implications on users that were using uppercase emails ... lets deal with these on case by case basis

**Comment by tomitrescak** [comment]
Actually, I ran a query and there are no duplicates
