### ISSUE TITLE
Walking past the edge of the screen looks strange

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#39]
Quite a few students were confused with how walking past the edge of the screen looks now. Saying move while facing the end of the screen makes Clara jump back instead of simply reappear on the other end. The image shows an example of where it happens.
![image](https://user-images.githubusercontent.com/26546072/110267637-580ed380-8014-11eb-983f-b40214ea1a6c.png)

**Comment by tomitrescak** [comment]
Hey, I have disabled animations ... we no longer get that smooth look, but it avoids other problems. Looks like animations are quite inconsitent across browsers. We can revisit this later if it is desired.
