### ISSUE TITLE
Visual glitches

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#41]
Many students have confirmed at today's lecture that they experience strange visual glitches. They reported seeing it in different browsers (Edge, Chrome). One of the students of AUT 2021 (Felix Lee) sent a video (enclosed). I was able to reproduce it in Brave browser (worked fine in Safari and Chrome).

https://user-images.githubusercontent.com/26546072/110271980-2f3f0c00-801d-11eb-8b1a-da825d858ad1.mp4

**Comment by antonwsu** [comment]
Felix said that he is using Chrome.

**Comment by antonwsu** [comment]
Here is a video from another student (Isaac Wu <20366937@student.westernsydney.edu.au>) who experienced this problem in Chrome and Edge.

https://user-images.githubusercontent.com/26546072/110402213-1ee76980-80cf-11eb-8bdd-6a5ed2fdb81c.mp4

**Comment by tomitrescak** [comment]
Again, I have disabled animations, this prevents these errors ... let me know if problems reappear. On staging now.

**Comment by antonwsu** [comment]
I'll ask students to test this on staging.

**Comment by tomitrescak** [comment]
No need to use staging .. all is live ...

**Comment by antonwsu** [comment]
This is great! Many students mentioned this in the QnA. When I asked them to email me about this, some said that I'll receive too many emails. This was the biggest issue so far in the new version. Great that it's fixed! IMO, we are going very well given how many changes you made. Well done!
