### ISSUE TITLE
Leaderboard issues with solutions that need to be approved

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#43]
A student Alp Durdag <19776460@student.westernsydney.edu.au> solved a problem with very few lines of code for Practical 5, Problem 1. The solution is correct and I approved it. Pressing: Approve solution, In competition, Recalculate the results. There is no reflection of this in the leaderboard. It still shows 0 solutions and 0 lines against his name for Practical 5.
<img width="711" alt="Screen Shot 2021-03-09 at 12 10 40 pm" src="https://user-images.githubusercontent.com/26546072/110403257-e6488f80-80d0-11eb-8976-899814c855f0.png">

**Comment by tomitrescak** [comment]
I have done "In Competition" + "Accept Solution" and all worked as expected,
That being said, it is quite confusing.

I have removed the option for "Accept Solution".
All you need to do is to press "In Competition" and "Out Competition".

The recalculate results is also removed (we may add it if you deem it necessary).

**Comment by antonwsu** [comment]
I would like to reopen this one. Just had a student who has completed Practical 5 problem 1 and required a very short solution to be approved. I approved it by selecting "In Competition". 3 hours later there is still no change in the leaderboard: https://claraworld.net/leaderboards/autumn-2021/practical-5-variables?i=KbQweP7bMqJ7nsypS&p=6yM6v7f6eXGk4ecFb The student is Afnan Alam
