### ISSUE TITLE
Cloning practicals/problems by default

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#44]
I think it would be a good idea to clone practicals/problems that we add to new schedules by default. In this way we will avoid messing up someone's schedule. This is a feature request rather than a bug report.

**Comment by antonwsu** [comment]
Another reason why cloning is best to be done by default is the use of points assigned to a problem. I often compile a practical from a number of problems that don't add up if you count the respective points, so I must change these all the time. Cloning by default will ensure that I will not mess up someone's schedule. The same goes for numbering problems. In one practical it's 3_1 and in another practical it will be 3_2.

**Comment by tomitrescak** [comment]
I'm not sure what you mean. If you select a "deep" clone it will do exactly what you want.

**Comment by antonwsu** [comment]
@tomitrescak What I want is for deep clone to be the default option whenever I add an existing practical to a schedule or a problem to a practical. At the moment for me to do the deep clone I first have to find a practical/problem, edit it and create a duplicate via deep clone. Only then I can add this cloned version to the practical/schedule. It would be much more user-friendly if I could add problems directly to practicals and practicals directly to schedules via deep clone. There is, essentially, no need for anything other than deep clone, so let's make it a default option.

**Comment by antonwsu** [comment]
We have frequent issues with practicals/problems not being cloned. Just now Chris has accidentally changed my major assignment and made it unavailable to WSU after setting the organisation to WSU-City. Things like this happen a lot. We really need to always clone rather than work by reference.
