### ISSUE TITLE
Update the list of unsupported browsers

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#46]
We've discovered that the lab computers (that use older version of IE and Edge) don't work with Clara well. For those old browsers we should display the "Browser not supported" message as we did before, so that users know what's going on.

**Comment by tomitrescak** [comment]
The site will now correctly detect explorer ... I have no access to old edge and microsoft makes it impossible to install. I'll go on monday to one of the labs and check it out. The problem is that they do not allow the web console.
