### ISSUE TITLE
Clara's World takes much longer to load

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#47]
I don't know whether this can be fixed. Feel free to close if not. After moving to the new version at the start of the semester it takes substantially longer to load Clara's World, while prior to the new version it was almost instant.

**Comment by tomitrescak** [comment]
No, the time is actually shorter ... yes you wait for initial request but you see the whole page rendered. Before, it send the bare minimum of html and then you were watiing for data with all the "loaders". 

We have three paths here: 
1. faster server
2. we disable the server rendering and have you looking at loaders
3. we leave it as it is

**Comment by antonwsu** [comment]
OK, let's leave it then. Hopefully Guang can help with allocating more resources on the server.

**Comment by antonwsu** [comment]
@tomitrescak The same 15 sec delay also happens when I simply request a link to a video via URL shortener (e.g. https:/claraworld.net/link/C4V1). There should be no rendering happening in this case, so the reason for the delay is probably something else.

**Comment by tomitrescak** [comment]
Anton, it's always about the server loop. Server receives the request, contacts the database and then gives you back the data.
If there is many users the performance goes down. Try to visit it at night. 

For example, that link opened in 4 seconds to me now.

**Comment by antonwsu** [comment]
4 seconds is also quite a long delay. Why wasn't it there before? What will happen if we have 10 other universities using the system?

**Comment by tomitrescak** [comment]
The wait will increase ... but the same would be in previous system as well. You would be waiting for your data.
If we have 10 universities we simply switch hosting to something more reasonable and scalable.

**Comment by tomitrescak** [comment]
@antonwsu can you test performance on staging? There was an issue that too many refresh tokens were stored and it was comparing it to > 40 tokens. Now I allow only two login tokens ... this means that you can only be logged in in 2 devices at the same time ... but I guess it should not be an issue to people. Once in school once at home.

Pls test and let me know . If you notice the difference then we can push it live.

**Comment by antonwsu** [comment]
Works like a charm now.
