### ISSUE TITLE
Grid tiles occasionally disappear

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#50]
I saw it many times while working on the new Major Assignment and a couple of students complained about this issue. Sometimes the tiles get replaced by question marks as if there is no Internet connection and they can't be loaded. See the enclosed screenshot. Usually a reload of the page helps, but this happens relatively frequently, so it's best to be fixed.
![Screen Shot 2021-03-25 at 3 10 04 pm](https://user-images.githubusercontent.com/26546072/112417842-7c8cde80-8d7c-11eb-8d58-6d4b4e61f926.png)

**Comment by tomitrescak** [comment]
It never happened to me :/ I will need a reproduction case unfortunately, otherwise I do not k is what I am fixing

**Comment by antonwsu** [comment]
Happens every second time when I'm opening the major assignment. Do you, maybe, keep reloading the tiles multiple times? This definitely happens when I'm offline. As soon as connection drops the tiles turn into question marks. In the past it was possible to work on practicals without Internet. Here is another example (despite being connected to Internet).
<img width="805" alt="Screen Shot 2021-03-25 at 5 53 31 pm" src="https://user-images.githubusercontent.com/26546072/112431198-4eff5f80-8d93-11eb-8790-134fdb8a9079.png">

**Comment by antonwsu** [comment]
For some reason it always happens to gold sacks only.

**Comment by antonwsu** [comment]
@tomitrescak, this happens with 100% probability now if you go to staging and run the major assignment. It seems to be related to playing animations.

**Comment by tomitrescak** [comment]
It does not happen to me :/ I really do not know how to simulate this ... and I have NO IDEA what the problem is.

**Comment by tomitrescak** [comment]
When it happens to you leave the window open and let's do the zoom.

**Comment by antonwsu** [comment]
I've been using Safari. Maybe that's the reason why you can't reproduce?

**Comment by antonwsu** [comment]
@tomitrescak This is another critical bug that would be good to fix. It only happens to me in Safari, but happens quite frequently.

**Comment by tomitrescak** [comment]
Please come an see me on Monday ... I cannot replicate this at all :/ I tried on my Mac .. but it works/

**Comment by antonwsu** [comment]
Just updated Safari to the latest version (Version 14.0.3 (15610.4.3.1.7, 15610)). The problem is still there.

**Comment by antonwsu** [comment]
A few students on Discord discussed having this issue. I've also received a couple of emails about it.

**Comment by antonwsu** [comment]
seems to be fixed in the new version.
