### ISSUE TITLE
Can't play multiple audio files at once

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#51]
While working on the Digger assignment I realised that only one audio file can be played at once. I can't play the theme music and sounds for picking up powers at the same time. I remember students complaining at the past that sometimes sounds don't work in the major assignment. This is because the game was moving too fast and the second sound is not being played if the first one hasn't finished playing yet.

**Comment by antonwsu** [comment]
@tomitrescak, if this is not difficult to do, could you please fix this soon? I need this for the major assignment.

**Comment by antonwsu** [comment]
@tomitrescak, it appears that multiple sounds can be played simultaneously. There are some issues with playing the same sound a number of times (e.g. collecting two leaves too fast would result in playing the corresponding sound only once).

**Comment by tomitrescak** [comment]
There is not much I can do here :/ Please reopen if needed
