### ISSUE TITLE
Can't modify an existing URL shortcut

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#52]
It is not currently possible to update an existing shortcut from Admin->Links. There is a corresponding button, but when I click on it and then try to save the result, I receive an error complaining that this shortcut already exists. There is a workaround, which is to delete the existing link and create a new one, but it would have been better to be able to edit the existing link without deleting it.

**Comment by tomitrescak** [comment]
Sevral issues solved and deployed to staging
