### ISSUE TITLE
Plagiarism checking doesn't work

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#53]
I receive the following error when I try checking for plagiarism through Clara's World:
"The requested URL /results/237973283 was not found on this server."

**Comment by tomitrescak** [comment]
MOSS has a retention of only couple of weeks, old reports are deleted .. this is not my issue :/

**Comment by tomitrescak** [comment]
I have added a dropdown menu that will allow you to re-generate the report.
I cannot even cache this as I would have to cache each individual comparison.

**Comment by antonwsu** [comment]
Works like a charm in the new version! Thanks a lot, Tomas!
