### ISSUE TITLE
Play button is occasionally disabled for no good reason

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#54]
While working on the major assignment I realised that sometimes the play button is greyed out after pressing the "Save" button, while there is nothing wrong with the code. The only thing that helps is then closing the tab and reloading.

**Comment by antonwsu** [comment]
I'm using staging and Chrome.

**Comment by antonwsu** [comment]
Further investigation showed that this happens when saving can't be completed for some reason. Pressing the save button causes a substantial delay that has to be interrupted by pressing the X button in the browser, after which the following message comes up saying "Save Failed. Failed to Fetch." (see picture below).
![Uploading Screen Shot 2021-04-08 at 10.19.50 am.png…]()

**Comment by antonwsu** [comment]
![Uploading Screen Shot 2021-04-08 at 10.19.50 am.png…]()

**Comment by tomitrescak** [comment]
I do not see the image

**Comment by antonwsu** [comment]
The image basically shows the error "Save Failed. Failed to Fetch."

**Comment by tomitrescak** [comment]
Anton, these errors are difficult to fix without a proper reproduction case

**Comment by antonwsu** [comment]
I think this happens when I open the same assignment in a different browser and login with the same account.

**Comment by antonwsu** [comment]
Haven't seen this for a while. Closing for now.
