### ISSUE TITLE
Frequent logouts

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#56]
I'm experiencing frequent logouts after latest changes on staging. Every time I refresh the page I get logged out.

**Comment by antonwsu** [comment]
Happens every time when I terminate the game in the major assignment by refreshing the browser or pressing the back button. Could it be related to interrupting the sound? 
<img width="374" alt="Screen Shot 2021-04-13 at 1 00 52 am" src="https://user-images.githubusercontent.com/26546072/114416476-12858d80-9bf4-11eb-8443-4720f0e1a910.png">

**Comment by tomitrescak** [comment]
This should be fixed
