### ISSUE TITLE
Feature request: setting z-index of a tile

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#57]
At present broken gold will hide behind the leaves in the major assignment. It would be good to be able to control which tile must remain in front.

**Comment by tomitrescak** [comment]
This is already possible with Sprites, which are loaded in that order. The way the layers work ordered from most behind to front:

- Background
- Grid
- Statics (trees ...)
- Sprites (the only ones ordered by zIndex)
- Players
- Drawing
