### ISSUE TITLE
Feature request: Changing the order of class appearance in tabs

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#58]
It would have been nice to be able to change the order in which tabs for different classes appear in the project.
For example, in the digger assignment I would want to have MyClara, Gold, Ghost rather than Ghost, MyClara, Gold.

**Comment by tomitrescak** [comment]
This is already possible:

![image](https://user-images.githubusercontent.com/2682705/114670798-bda65c00-9d46-11eb-9b10-562452ec8ed5.png)

Just use "Move Left" "Move right"
