### ISSUE TITLE
Correct English in Error message

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#59]
Please change the message to something like: "No Internet connection detected".

<img width="368" alt="Screen Shot 2021-04-22 at 9 11 51 am" src="https://user-images.githubusercontent.com/26546072/115632351-df0cd680-a34a-11eb-806d-baac461a93c6.png">

**Comment by tomitrescak** [comment]
Unfortunately this is message from the browser, I do not decide this message.
