### ISSUE TITLE
Debugger doesn't show all local variables

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#60]
As I was debugging one of the practicals I realised that loop index variables are not displayed. This is basically all I want to see when debugging, the values of index variables (i and k in the screenshot) . It would be nice to fix it.
<img width="1299" alt="Screen Shot 2021-04-23 at 9 27 43 am" src="https://user-images.githubusercontent.com/26546072/115797085-68d5a600-a416-11eb-8130-85ca251e11cb.png">

**Comment by tomitrescak** [comment]
Just tested and it should be fixed
