### ISSUE TITLE
Nasty line count bug

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#61]
Adding a comment that starts with //* will result in the lines that follow after not being counted.
Example from a student:

class MyClara extends Clara { 
    /**
     * In the 'run()' method you can write your program for Clara 
     */

    /*
    Pre-condition: to make Clara scan each line and detect leaf,
    place leaf in identical box in next chamber.

    Post-condition: Clara needs to scan each row individually,
    detect where the leaf is, move to the mid-point in the map
    to cross the bridge, scan next chamber and place leaf.
    */
    
    int steps;
    int mid;

    void run() {

    turnRight();
    //***voids***

followed by 140 lines of code.

Result -> Your solution has 3 lines of code, while three star solution has 90 lines of code.

**Comment by antonwsu** [comment]
This issue is still there in the new version.

**Comment by tomitrescak** [comment]
Fixed

**Comment by antonwsu** [comment]
It's still there on staging.
<img width="1671" alt="Screen Shot 2021-07-29 at 6 52 24 am" src="https://user-images.githubusercontent.com/26546072/127394353-aa36452f-6111-46bb-baa1-e5ae23efd224.png">
