### ISSUE TITLE
ReadInt prompt and Comment Preview combine

### ISSUE THREAD

**Issue by Dean-P** [tomitrescak/clara-support#63]
Sample code:
```
void run()
{
    readInt("readInt message");
}
```
1. Go to any marking view and select some exercise
2. Run `readInt()` as above
3. Go to comment view
4. Enter some comment into text area 
5. Click "Preview" button

Preview screen will show comment then the readInt prompt with the prior message:
![comment](https://user-images.githubusercontent.com/9068794/118259751-db591380-b4f4-11eb-9b78-5f829f27c395.png)

This also goes the other way:
1. Refresh marking view to reset preview and go to exercise
2. Go to comment view
3. Enter some comment
4. Go to Board view
5. Run `readInt()` as above

The readInt() prompt will contain the comment text:
![readInt](https://user-images.githubusercontent.com/9068794/118260012-2a06ad80-b4f5-11eb-8fbe-1eb16c7bdd40.png)

**Comment by tomitrescak** [comment]
Finally fixed
