### ISSUE TITLE
Files get overridden in the major assignment

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#64]
Multiple students (I would say around 5) have contacted me with the request to restore their Major Assignment code from history because it was overridden. In all those requests one of the classes (e.g. Ghost) was completely replaced by another class (e.g Gold). One student told me that this is probably because he had the assignment open in multiple browsers at the same time. Please investigate.

**Comment by tomitrescak** [comment]
I have done a lot of changes in the way files are handled in the tabbed editor. I'll close this for now, until this reappears.
