### ISSUE TITLE
Rounding to an int does not correctly work.

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#68]
Below is a bug report from a student.
Hi Anton, I am typing this email to let you know that there might be a bug with Clara's world.

        double y = 2.5;
        int z = (int) y;

        System.out.println(z);

Running the code above (taken from the lecture slides) the return value of z returns 2.5
while it should be returning 2 as it is being casted into a int type.
I have double checked this code with an online java compiler and the correct value of 2 is being printed. On Clara's world it prints 2.5. I am not sure why it is doing this. But a way to solve it for now is just doing

int z = (int) y / 1;

Dividing it by 1 it forces it to be a int. Which works for now.

If I am mistaken, please email me back on what I'm doing wrong.

Thanks for your time.

**Comment by tomitrescak** [comment]
Yah, casting is not supported. I am working on a new compiler where it will be. I will also drop the size of the compiler from 2mb to 500kb and it will create a foundation for python support


Dr Tomas Trescak

Director of Academic Program Undergraduate ICT
Senior Lecturer In Intelligent Systems
School of Computer, Data and Mathematical Sciences
Western Sydney University | Locked Bag 1797 Penrith NSW 2751



P: (02) 9685 4744<tel://02%209685%204744/> | M: 0487 261 213<tel://0487%20261%20213/>
E: ***@***.******@***.***>



We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D’harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.



[UWS LOGO]

________________________________
From: antonwsu ***@***.***>
Sent: Monday, June 7, 2021 11:35:11 AM
To: tomitrescak/clara-support ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomitrescak/clara-support] Rounding to an int does not correctly work. (#68)


Below is a bug report from a student.
Hi Anton, I am typing this email to let you know that there might be a bug with Clara's world.

    double y = 2.5;
    int z = (int) y;

    System.out.println(z);


Running the code above (taken from the lecture slides) the return value of z returns 2.5
while it should be returning 2 as it is being casted into a int type.
I have double checked this code with an online java compiler and the correct value of 2 is being printed. On Clara's world it prints 2.5. I am not sure why it is doing this. But a way to solve it for now is just doing

int z = (int) y / 1;

Dividing it by 1 it forces it to be a int. Which works for now.

If I am mistaken, please email me back on what I'm doing wrong.

Thanks for your time.

**Comment by tomitrescak** [comment]
Fixed with the new compiler
