### ISSUE TITLE
$stack is not defined - Java Compiler

### ISSUE THREAD

**Issue by sententia** [tomitrescak/clara-support#71]
While testing out the new java compiler come across the following problem. World #1 $stack is not defined. 

The code was some simple testing of class level variables and methods. 

```java
class MyClara extends Clara { 
    /**
     * In the 'run()' method you can write your program for Clara 
     */
     int test;
    void run() {
        // TODO: Write your code below
        move();
        turnRight();
        for(int i = 0; i<3; i++) {
            move();
        }
    }

    void turnRight() {
        turnLeft();
        turnLeft();
    }
}
```

Here is the error shown. 

![Screen Shot 2021-06-21 at 5 00 45 pm](https://user-images.githubusercontent.com/1278767/122720305-a50c7200-d2b2-11eb-9841-80645ca4e768.png)

**Comment by tomitrescak** [comment]
Hi, this is solved. I added about 300 other features as well. Please keep on testing ;)

**Comment by tomitrescak** [comment]
Going to close this now. The new version is now live. It is of utmost importance that you guys test it thoroughly
