### ISSUE TITLE
Feature request: Edit history should open with the last edit first

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#72]
It's more convenient to open edit history starting with the last edit. Another improvement request is to make the <- button navigate to the last edit when at edit 0.

**Comment by tomitrescak** [comment]
Done! I also added the rewind and fast-forward buttons taking you to the first and last record. I also added a nicer number button control

![image](https://user-images.githubusercontent.com/2682705/152613701-67938f63-4068-4539-aca8-ce95f84d40c9.png)
