### ISSUE TITLE
Clara's World appears white instead of green

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#84]
Default Appearance (Supposed to be green)
<img width="477" alt="Screen Shot 2021-07-14 at 5 18 48 pm" src="https://user-images.githubusercontent.com/26546072/125579937-a83f7a4b-118e-4b27-a3f9-0e30172b04b7.png">

Light Appearance (Supposed to be white)
<img width="419" alt="Screen Shot 2021-07-14 at 5 19 27 pm" src="https://user-images.githubusercontent.com/26546072/125580079-d82b08b2-423a-44fa-aa34-972ec097c98b.png">

**Comment by tomitrescak** [comment]
Fixed
