### ISSUE TITLE
Cheat detection doesn't work as expected

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#85]
For Spring 2021 - > 1.1 there is a non-obvious correct solution, which is

    void run() {
        // TODO: Write your code below
        move();
        turnLeft();
        move();
        turnRight();
        move();
        move();
    }

The compiler complains about this solution being invalid (requires manual validation by the tutor) due to completing in 6 lines of code / 6 steps. My understanding is that setting cheat detection to "2" should stop it from complaining if solution has more than 2 lines of code, but it continues complaining.

**Comment by tomitrescak** [comment]
Fixed, I wonder how come this did not pop up before. This bug has been there for years!
