### ISSUE TITLE
Sokoban: testLevelComplete() no longer works as expected

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#91]
I need help with fixing testLevelComplete in Sokoboan (AUT 2021 -> 7.2 and 7.3).

Test it with putting the following code inside act().

        if ( testLevelComplete() )
            showWarning("Level Complete!");

It's supposed to only return true when mushrooms are positioned on top of all GhostWalls, but it's enough to put mushrooms on top of 2. 
![Screen Shot 2021-07-15 at 2 30 40 pm](https://user-images.githubusercontent.com/26546072/125729177-1619d653-08a8-4db5-86e3-5ab7d83b5551.png)

**Comment by tomitrescak** [comment]
Fixed on live and staging
