### ISSUE TITLE
Can't add admins to new organisations

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#98]
I've created a new organisation "WACM" for the student club and am unable to add the student as an admin for it. Creating a new account doesn't work (because it already exist) and typing it in the search field doesn't show any results.

**Comment by tomitrescak** [comment]
Yes, the student needs to join the organisation first I am afraid. Otherwise there would be a mess in filtering the data. Once he joins the organisation you can make him admin!
